name: 이미지 빌드 & 푸쉬
on:
  workflow_call:
    outputs:
      image-url:
        value: ${{ jobs.build.outputs.image-url }}
    inputs:
      image-name:
        required: true
        type: string
      image-tag:
        required: true
        type: string
      spring-profile:
        required: true
        type: string
    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_TOKEN:
        required: true

jobs:
  build:
    runs-on: [ ubuntu-latest ]
    name: 이미지 빌드하기

    outputs:
      image-url: ${{ steps.build-image.outputs.image-url }}

    permissions:
      id-token: write
      contents: read

    steps:
      - name: GitHub 에서 레포 받아오기
        uses: actions/checkout@v3

      - name: JDK17 준비하기
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Docker Hub 로그인하기
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Gradle 준비하기
        uses: gradle/actions/setup-gradle@v3

      - name: 이미지 빌드하고 푸쉬하기
        id: build-image
        run: |
          chmod +x jib.sh &&
          chmod +x ./gradlew &&
          /bin/bash jib.sh \
            ${{ inputs.image-name }} \
            ${{ inputs.image-tag }} \
            ${{ inputs.spring-profile }} &&
          echo "image-url=${{ inputs.image-name }}:${{ inputs.image-tag }}" >> $GITHUB_OUTPUT
